[package]
name = "poker-solver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units=1

[net]
git-fetch-with-cli = true

[dependencies]
rust_poker =  { version = "0.1.14" }
rayon = {version = "1.5.1"}
permutation = "0.2.5"
enum_dispatch = "0.3.7"